version: '3'
services:
  teste-habilidade-php:
    build: .
    depends_on:
      - mysql
    ports:
    - 8081:80
    working_dir: /var/www/html
    volumes: 
      - .:/var/www/html
    networks:
      - my_net
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3308:3306"
    volumes:
      - ./database_seed/teste_habilidade_php.sql:/docker-entrypoint-initdb.d/teste_habilidade_php.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: teste_habilidade_php
      MYSQL_PASSWORD: 123456
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
